In [1]:
import pandas as pd
import numpy as np

In [12]:
data = pd.read_csv("./230224_통일강화대교_utf_8.csv", encoding="CP949")
data

                    시간  강화수위  통일수위
0      2022-12-01 0:00  1.36  0.10
1      2022-12-01 0:10  1.26  0.27
2      2022-12-01 0:20  1.14  0.43
3      2022-12-01 0:30  1.03  0.61
4      2022-12-01 0:40  0.91  0.76
...                ...   ...   ...
6043  2023-01-11 23:10  0.91  1.81
6044  2023-01-11 23:20  0.76  1.76
6045  2023-01-11 23:30  0.61  1.68
6046  2023-01-11 23:40  0.47  1.57
6047  2023-01-11 23:50  0.31  1.43

[6048 rows x 3 columns]